name: Java CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    env:
      DISPLAY: ":99"
      GITHUB_HEADLESS: true

    steps:
      - name: Set up repository
        uses: actions/checkout@v4

      - name: Merge to master
        run: git checkout --progress --force ${{ github.sha }}

      # ✅ Headless display for JavaFX (Linux only)
      - name: Start virtual display (Xvfb)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          Xvfb :99 -ac &
          sleep 3

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK 17 with JavaFX
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: jdk+fx

      - name: Build and check with Gradle
        run: ./gradlew clean build --stacktrace

      - name: Upload coverage reports to Codecov
        if: runner.os == 'Linux'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
